version: 2.1


orbs:
  golang: cci-orb/golang@0.1.4
executors:
  macos-executor: cci-orb/golang@0.1.4

jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /home/circleci/go/src/github.com/shirou/gopsutil
    environment:
      GOPATH: /home/circleci/go
    steps:
      - run:
          command: |
            echo -e 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - checkout
      - run:
          command: make init_tools
      - run:
          command: dep ensure
      - run:
          command: go build -v
      - run:
          command: make build_test
  macos:
    executor: macos-executor
    working_directory: /home/circleci/go/src/github.com/shirou/gopsutil
    environment:
      GOPATH: /home/circleci/go
    steps:
      - run:
          command: |
            echo -e 'export PATH=$GOPATH/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
      - checkout
      - run:
          command: make init_tools
      - run:
          command: dep ensure
      - run:
          command: go build -v
      - run:
          command: make macos_test

workflows:
  version: 2
  test:
    jobs:
      - test
      - macos
